--1. What was the most common purpose of loans by state in 2018?
SELECT PURPOSE_OF_LOAN 
  FROM (
        SELECT PURPOSE_OF_LOAN, COUNT(*)
          FROM LOANS
         GROUP BY PURPOSE_OF_LOAN
         ORDER BY COUNT(*) DESC
       )
  WHERE ROWNUM = 1;

--2. What are the average age and annual income of the borrowers that got loans for Home Improvement/Rehabilitation? 

        SELECT AGE_OF_BORROWER, COUNT(*) AS QTT, TRUNC(AVG(BORROWERS_ANNUAL_INCOME), 2) AS BORROWERS_ANNUAL_INCOME
          FROM LOANS
          WHERE PURPOSE_OF_LOAN = 'Home Improvement/Rehabilitation'
         GROUP BY AGE_OF_BORROWER
         ORDER BY COUNT(*) DESC

--3. What is the most common occupancy of the properties of the borrowers with the highest unpaid principal balance in California? These borrowers are first time home buyers?

SELECT OCCUPANCY_CODE
     , CASE FIRST_TIME_HOME_BUYER WHEN 1 THEN 'Yes' WHEN 2 THEN 'No' ELSE ' Not available' END FIRST_TIME_HOME_BUYER, count(*)
          FROM LOANS
          WHERE ACQ_UNPAID_PRINCIP_BALANCE_UPB = (SELECT MAX(ACQ_UNPAID_PRINCIP_BALANCE_UPB)
                                                    FROM LOANS)                                                    
         GROUP BY OCCUPANCY_CODE, FIRST_TIME_HOME_BUYER
         ORDER BY COUNT(*) DESC

--4. Are there any records that appear in both Fannie Mae and Freddie Mac data? How would you remove duplicates?
SELECT T1.ROWID, T1.*
FROM LOANS T1
WHERE EXISTS (SELECT 1 
                FROM LOANS T2
                WHERE
                     T1.RECORD_NUMBER = T2.RECORD_NUMBER
                 AND T1.US_POSTAL_STATE_CODE = T2.US_POSTAL_STATE_CODE
                 AND T1.METROPOLITAN_STA_AREA_MSA_CODE = T2.METROPOLITAN_STA_AREA_MSA_CODE
                 AND T1.COUNTY_2010_CENSUS = T2.COUNTY_2010_CENSUS
                 AND T1.CENSUS_TRACT_2010_CENSUS = T2.CENSUS_TRACT_2010_CENSUS
                 AND T1."2010_CENSUS_TRACT_PCT_MINORITY" = T2."2010_CENSUS_TRACT_PCT_MINORITY"
                 AND T1."2010_CENSUS_TRACT_MEDIAN_INCOM" = T2."2010_CENSUS_TRACT_MEDIAN_INCOM"
                 AND T1.LOCAL_AREA_MEDIAN_INCOME = T2.LOCAL_AREA_MEDIAN_INCOME
                 AND T1.TRACT_INCOME_RATIO = T2.TRACT_INCOME_RATIO
                 AND T1.BORROWERS_ANNUAL_INCOME = T2.BORROWERS_ANNUAL_INCOME
                 AND T1.AREA_MEDIAN_FAMILY_INCOME_2018 = T2.AREA_MEDIAN_FAMILY_INCOME_2018
                 AND T1.BORROWER_INCOME_RATIO = T2.BORROWER_INCOME_RATIO
                 AND T1.ACQ_UNPAID_PRINCIP_BALANCE_UPB = T2.ACQ_UNPAID_PRINCIP_BALANCE_UPB
                 AND T1.PURPOSE_OF_LOAN = T2.PURPOSE_OF_LOAN
                 AND T1.FEDERAL_GUARANTEE = T2.FEDERAL_GUARANTEE
                 AND T1.NUMBER_OF_BORROWERS = T2.NUMBER_OF_BORROWERS
                 AND T1.FIRST_TIME_HOME_BUYER = T2.FIRST_TIME_HOME_BUYER
                 AND T1.BORROWER_RACE_1 = T2.BORROWER_RACE_1
                 AND T1.BORROWER_RACE_2 = T2.BORROWER_RACE_2
                 AND T1.BORROWER_RACE_3 = T2.BORROWER_RACE_3
                 AND T1.BORROWER_RACE_4 = T2.BORROWER_RACE_4
                 AND T1.BORROWER_RACE_5 = T2.BORROWER_RACE_5
                 AND T1.BORROWER_ETHNICITY = T2.BORROWER_ETHNICITY
                 AND T1.CO_BORROWER_RACE_1 = T2.CO_BORROWER_RACE_1
                 AND T1.CO_BORROWER_RACE_2 = T2.CO_BORROWER_RACE_2
                 AND T1.CO_BORROWER_RACE_3 = T2.CO_BORROWER_RACE_3
                 AND T1.CO_BORROWER_RACE_4 = T2.CO_BORROWER_RACE_4
                 AND T1.CO_BORROWER_RACE_5 = T2.CO_BORROWER_RACE_5
                 AND T1.CO_BORROWER_ETHNICITY = T2.CO_BORROWER_ETHNICITY
                 AND T1.BORROWER_GENDER = T2.BORROWER_GENDER
                 AND T1.CO_BORROWER_GENDER = T2.CO_BORROWER_GENDER
                 AND T1.AGE_OF_BORROWER = T2.AGE_OF_BORROWER
                 AND T1.AGE_OF_CO_BORROWER = T2.AGE_OF_CO_BORROWER
                 AND T1.OCCUPANCY_CODE = T2.OCCUPANCY_CODE
                 AND T1.RATE_SPREAD = T2.RATE_SPREAD
                 AND T1.HOEPA_STATUS = T2.HOEPA_STATUS
                 AND T1.PROPERTY_TYPE = T2.PROPERTY_TYPE
                 AND T1.LIEN_STATUS = T2.LIEN_STATUS
                 AND T1.ROWID <> T2.ROWID
                 AND T1.ENTERPRISE_FLAG <> T2.ENTERPRISE_FLAG);
                 
--How would you remove duplicates?
DELETE FROM LOANS WHERE ROWID <> 
(SELECT MAX(T1.ROWID)
FROM LOANS T1
WHERE EXISTS (SELECT 1 
                FROM LOANS T2
                WHERE
                     T1.RECORD_NUMBER = T2.RECORD_NUMBER
                 AND T1.US_POSTAL_STATE_CODE = T2.US_POSTAL_STATE_CODE
                 AND T1.METROPOLITAN_STA_AREA_MSA_CODE = T2.METROPOLITAN_STA_AREA_MSA_CODE
                 AND T1.COUNTY_2010_CENSUS = T2.COUNTY_2010_CENSUS
                 AND T1.CENSUS_TRACT_2010_CENSUS = T2.CENSUS_TRACT_2010_CENSUS
                 AND T1."2010_CENSUS_TRACT_PCT_MINORITY" = T2."2010_CENSUS_TRACT_PCT_MINORITY"
                 AND T1."2010_CENSUS_TRACT_MEDIAN_INCOM" = T2."2010_CENSUS_TRACT_MEDIAN_INCOM"
                 AND T1.LOCAL_AREA_MEDIAN_INCOME = T2.LOCAL_AREA_MEDIAN_INCOME
                 AND T1.TRACT_INCOME_RATIO = T2.TRACT_INCOME_RATIO
                 AND T1.BORROWERS_ANNUAL_INCOME = T2.BORROWERS_ANNUAL_INCOME
                 AND T1.AREA_MEDIAN_FAMILY_INCOME_2018 = T2.AREA_MEDIAN_FAMILY_INCOME_2018
                 AND T1.BORROWER_INCOME_RATIO = T2.BORROWER_INCOME_RATIO
                 AND T1.ACQ_UNPAID_PRINCIP_BALANCE_UPB = T2.ACQ_UNPAID_PRINCIP_BALANCE_UPB
                 AND T1.PURPOSE_OF_LOAN = T2.PURPOSE_OF_LOAN
                 AND T1.FEDERAL_GUARANTEE = T2.FEDERAL_GUARANTEE
                 AND T1.NUMBER_OF_BORROWERS = T2.NUMBER_OF_BORROWERS
                 AND T1.FIRST_TIME_HOME_BUYER = T2.FIRST_TIME_HOME_BUYER
                 AND T1.BORROWER_RACE_1 = T2.BORROWER_RACE_1
                 AND T1.BORROWER_RACE_2 = T2.BORROWER_RACE_2
                 AND T1.BORROWER_RACE_3 = T2.BORROWER_RACE_3
                 AND T1.BORROWER_RACE_4 = T2.BORROWER_RACE_4
                 AND T1.BORROWER_RACE_5 = T2.BORROWER_RACE_5
                 AND T1.BORROWER_ETHNICITY = T2.BORROWER_ETHNICITY
                 AND T1.CO_BORROWER_RACE_1 = T2.CO_BORROWER_RACE_1
                 AND T1.CO_BORROWER_RACE_2 = T2.CO_BORROWER_RACE_2
                 AND T1.CO_BORROWER_RACE_3 = T2.CO_BORROWER_RACE_3
                 AND T1.CO_BORROWER_RACE_4 = T2.CO_BORROWER_RACE_4
                 AND T1.CO_BORROWER_RACE_5 = T2.CO_BORROWER_RACE_5
                 AND T1.CO_BORROWER_ETHNICITY = T2.CO_BORROWER_ETHNICITY
                 AND T1.BORROWER_GENDER = T2.BORROWER_GENDER
                 AND T1.CO_BORROWER_GENDER = T2.CO_BORROWER_GENDER
                 AND T1.AGE_OF_BORROWER = T2.AGE_OF_BORROWER
                 AND T1.AGE_OF_CO_BORROWER = T2.AGE_OF_CO_BORROWER
                 AND T1.OCCUPANCY_CODE = T2.OCCUPANCY_CODE
                 AND T1.RATE_SPREAD = T2.RATE_SPREAD
                 AND T1.HOEPA_STATUS = T2.HOEPA_STATUS
                 AND T1.PROPERTY_TYPE = T2.PROPERTY_TYPE
                 AND T1.LIEN_STATUS = T2.LIEN_STATUS
                 AND T1.ROWID <> T2.ROWID))


--Extra: Is there any other query that you think would bring relevant information?
--What are the average age and gender from the first time buyers?
SELECT AGE_OF_BORROWER 
, CASE BORROWER_GENDER WHEN 1 THEN 'Male' 
                       WHEN 2 THEN 'Female' 
                       ELSE 'Not provided/Applicable/Available' END AS BORROWER_GENDER
, COUNT(*) QTT
FROM DB_AL.LOANS 
WHERE FIRST_TIME_HOME_BUYER =  1 
GROUP BY AGE_OF_BORROWER 
, CASE BORROWER_GENDER WHEN 1 THEN 'Male' 
                       WHEN 2 THEN 'Female' 
                        ELSE 'Not provided/Applicable/Available' END; 
